name: dart_nn
description: A simple NeuralNetwork library. You can create a simple NeuralNetwork brain with any number of inputs, outputs and hidden nodes, but the hidden layer can only be of 1 layer.
version: 1.0.4
homepage: https://github.com/vickylance/dart_nn
repository: https://github.com/vickylance/dart_nn
issue_tracker: https://github.com/vickylance/dart_nn/issues

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path: ^1.6.4
  dart_numerics: ^0.0.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.11.1
  csv: ^4.0.3
